# Generated by Django 5.1.5 on 2025-02-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
    ]
